substitutions:
  # Device Identity
  name: sungoldpower-lfp
  friendly_name: "SunGoldPower LFP"

  # Hardware Pinout
  uart_rx_pin: GPIO21
  relay_pin: GPIO16
  status_led_pin: GPIO23

  # Path prefix for local repository checkout (default to current directory)
  # Useful when extending this config locally.
  sungoldpowerlfp_component_source: "components"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ap:
    ssid: "${friendly_name} Fallback"

captive_portal:

improv_serial:

esp32_improv:
  authorizer: none

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: "!secret ota_password"

web_server:
  version: 3

light:
  - platform: status_led
    id: light_led
    name: LED
    icon: "mdi:led-on"
    pin:
      number: ${status_led_pin}
      inverted: true

external_components:
  - source: ${sungoldpowerlfp_component_source}
    id: "sungoldpowerlfp_component"
    components: ["sungoldpower_lfp"]

uart:
  id: uart_bus
  rx_pin: ${uart_rx_pin}
  baud_rate: 2400
# Inverter Component
sungoldpower_lfp:
  id: inverter
  uart_id: uart_bus
  update_interval: 10s

switch:
  - platform: gpio
    pin: ${relay_pin}
    name: "Inverter Power Control"
    id: inverter_relay
    icon: "mdi:power"

# Telemetry Sensors
sensor:
  - platform: sungoldpower_lfp
    id: sungoldpower_sensors
    sungoldpower_lfp_id: inverter
    ip_voltage:
      name: "Input Voltage"
      id: ip_voltage
    ip_fault_voltage:
      name: "Input Fault Voltage"
      id: ip_fault_voltage
    op_voltage:
      name: "Output Voltage"
      id: op_voltage
    op_current:
      name: "Output Current"
      id: op_current
    op_frequency:
      name: "Output Frequency"
      id: op_frequency
    battery_voltage:
      name: "Battery Voltage"
      id: battery_voltage
    temperature:
      name: "Temperature"
      id: inverter_temperature
      internal: true

# Status Binary Sensors
binary_sensor:
  - platform: sungoldpower_lfp
    id: sungoldpower_binary_sensors
    sungoldpower_lfp_id: inverter
    utility_fail:
      name: "Utility Fail"
      id: utility_fail
    battery_low:
      name: "Battery Low"
      id: battery_low
    avr_active:
      name: "AVR Active"
      id: avr_active
      internal: true
    ups_failed:
      name: "UPS Failed"
      id: ups_failed
    line_interactive:
      name: "Line Interactive Type"
      id: line_interactive
    test_progress:
      name: "Test in Progress"
      id: test_progress
    shutdown_active:
      name: "Shutdown Active"
      id: shutdown_active
    beeper_on:
      name: "Beeper On"
      id: beeper_on
      internal: true
